# Generated by Django 4.2.6 on 2023-11-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(blank=True, max_length=125, null=True, verbose_name='Mağaza Adı')),
                ('enlem', models.FloatField(blank=True, null=True, verbose_name='Mağaza Enlem')),
                ('boylam', models.FloatField(blank=True, null=True, verbose_name='Mağaza Boylam')),
                ('logo', models.TextField(blank=True, max_length=455, null=True, verbose_name='Mağaza Logo')),
            ],
        ),
    ]
