# Generated by Django 4.2.6 on 2023-11-06 17:24

from django.db import migrations
from django.contrib.gis.geos import Point

def populate_location(apps, schema_editor):
    Magaza = apps.get_model('core', 'Magaza')
    for magaza in Magaza.objects.all():
        if magaza.enlem is not None and magaza.boylam is not None:
            magaza.location = Point(magaza.enlem, magaza.boylam)
            magaza.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_magaza_location'),
    ]

    operations = [
        migrations.RunPython(populate_location),
    ]
