# Generated by Django 5.1.1 on 2025-04-10 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_historicalmagaza'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmagaza',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Mağaza', 'verbose_name_plural': 'historical Mağazalar'},
        ),
        migrations.AlterModelOptions(
            name='magaza',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mağaza', 'verbose_name_plural': 'Mağazalar'},
        ),
        migrations.AddField(
            model_name='historicalmagaza',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AddField(
            model_name='historicalmagaza',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AddField(
            model_name='historicalmagaza',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Mağaza Sahibi'),
        ),
        migrations.AddField(
            model_name='historicalmagaza',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AddField(
            model_name='magaza',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AddField(
            model_name='magaza',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AddField(
            model_name='magaza',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='magazas', to=settings.AUTH_USER_MODEL, verbose_name='Mağaza Sahibi'),
        ),
        migrations.AddField(
            model_name='magaza',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AddIndex(
            model_name='magaza',
            index=models.Index(fields=['owner', 'active'], name='core_magaza_owner_i_32688f_idx'),
        ),
        migrations.AddIndex(
            model_name='magaza',
            index=models.Index(fields=['ad'], name='core_magaza_ad_0b705d_idx'),
        ),
    ]
